### ISSUE TITLE
[Bug] Resizing doesn't work

### ISSUE THREAD

**Issue by alexmozaidze** [optozorax/egui-macroquad#11]
When trying to resize windows/panels it doesn't work diagonally and horizontally, but vertically it, for some reason, decides to not resize itself but to move on the Y axis following the cursor

**Comment by alexmozaidze** [comment]
Resizing seems to work only if there are elements? That's weird

**Comment by optozorax** [comment]
Hi @alexmozaidze, sorry for the late answer, I have no time for this recently. Does this bug happens exactly in `egui-macroquad` and it can be reproduced when using `egui` trough [egui_eframe](https://github.com/emilk/eframe_template/). I think this bug related to the main egui repository.

**Comment by alexmozaidze** [comment]
It seems to be egui issue, not this crate's. I found out about it after some time and I kind of forgot that I made this issue. Closing.
