### ISSUE TITLE
Update version of macroquad in Cargo.toml

### ISSUE THREAD

**Issue by Pebaz** [optozorax/egui-macroquad#2]
It's a bit out of date =)

Could you set it to use "any version above ..." rather than use an explicit version? That way it would work with all current and future versions of Macroquad!

**Comment by optozorax** [comment]
Done, `0.3.0` is released with `macroquad` `0.3.0`.

> any version

As I understand if `macroquad` releases version `0.3.1`, this crate will work by just `cargo update`? Because `0.3.0` is interpreted as `^0.3.0`.

**Comment by Pebaz** [comment]
Great! Thanks for the quick response! :)
