### ISSUE TITLE
Set render target

### ISSUE THREAD

**Issue by brianwp3000** [optozorax/egui-macroquad#23]
Is it possible for equi-macroquad to use the current macroquad camera settings? Ideally it would use the camera's zoom/rotation/etc, but most important is the current camera's render_target.
I want to be able to render egui to a texture, but it's not currently possible with egui-macroquad.

**Comment by optozorax** [comment]
I'm afraid this is not possible because of core crate [`egui-miniquad`](https://github.com/not-fl3/egui-miniquad) architecture. There really nothing to tweak on `egui-macroquad` side.
