### ISSUE TITLE
Rendering Broken

### ISSUE THREAD

**Issue by LagMeester4000** [optozorax/egui-macroquad#3]
This is what happens when I run the example in a fresh clone of the repo:

![image](https://user-images.githubusercontent.com/33186092/120449291-97d52500-c38f-11eb-903b-c812050b99b1.png)

![image](https://user-images.githubusercontent.com/33186092/120449480-bcc99800-c38f-11eb-940e-bc988fff0376.png)

All of the input works, but the rendering is messed up. I tried running the egui-miniquad example too, to see if the issue was there instead, but the egui-miniquad build displayed normally.

**Comment by optozorax** [comment]
If `egui-miniquad` works nice, then problem is solved in [this commit](https://github.com/not-fl3/egui-miniquad/commit/376e7a226dec635d79fb3000b772f1001cc10b11). But this commit is not published to `crates.io`, so for now please use local copy of `egui-macroquad` with changed `Cargo.toml`
```toml
[dependencies]
egui-miniquad = { git = "https://github.com/not-fl3/egui-miniquad" }
``` 

I will publish new version of `egui-macroquad` with this issue being fixed when new version of `egui-miniquad` will be available.

**Comment by LagMeester4000** [comment]
It works! Thanks for the quick reply.
