### ISSUE TITLE
Using `egui_extra` with egui_macroquad.

### ISSUE THREAD

**Issue by deft01** [optozorax/egui-macroquad#31]
Hi, I have a question about egui_extra.
Since this crate is very usefull, I was wondering how can I use it with a diffrent renderer (ex: bevy, macroquad etc.).
I'm facing the problem there is no implementation of egui_extra for `macroquad`.
This cause this obvious error : 
```rust
error[E0308]: mismatched types
   --> src/table_view.rs:16:43
    |
16  |         let mut table = TableBuilder::new(ui)
    |                         ----------------- ^^ expected struct `egui::ui::Ui`, found struct `egui_macroquad::egui::Ui`
    |                         |
    |                         arguments to this function are incorrect
    |
    = note: struct `egui_macroquad::egui::Ui` and struct `egui::ui::Ui` have similar names, but are actually distinct types
```
I believe there is a way to do it because it is very usefull. But I wasnt able to find the trick.

**Comment by optozorax** [comment]
Maybe you have conflicting versions of `egui` and `egui-macroquad`? There are new version on crates.io up to the latest egui, try these.

**Comment by deft01** [comment]
I was using a different version of egui and egui_extra ! The fix is to use the same version of egui and egui_extra !
