### ISSUE TITLE
Re-export egui crate

### ISSUE THREAD

**Issue by SpyrosRoum** [optozorax/egui-macroquad#7]
Currently I need to manually add egui as a dependency to my project, this has the con that a new version of egui might be released that has some breaking changes and I might update to it before this crate gets a chance to update, which could cause headaches

Alternatively maybe mention in the README that egui needs to be listed as a dependecy and which egui version you support

**Comment by optozorax** [comment]
Yes, that makes sense. Added re-exports of the `egui` and `macroquad` in `0.6.1` version.
