### ISSUE TITLE
Consider turning off default-features for macroquad

### ISSUE THREAD

**Issue by noc7c9** [optozorax/egui-macroquad#9]
I'm attempting to use [kira](https://github.com/tesselode/kira) with both egui and macroquad. Unfortunately macroquad and kira have a native dependency conflict.

The solution is to disable the default `audio` feature on macroquad but I'm unable to do so because `egui-macroquad` keeps them on.

**Comment by optozorax** [comment]
Hi, sorry about late answer. I have no spare time, so please make a PR which will solve your issue, and I will accept it.
